# my-go-packages task-readme-github-pages.yml

platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: 1.20.1

inputs:
  - name: my-go-packages

outputs:
  - name: my-go-packages-updated

run:
  path: ./my-go-packages/ci/scripts/readme-github-pages.sh
  # args: [-debug]
